#!/usr/bin/env php
<?php

use Koneksi\Server;
use Koneksi\Request;
use Koneksi\Response;

require 'vendor/autoload.php';

array_shift($argv);

if (empty($argv)) {
	$port = 80;
} else {
	$port = array_shift($argv);
}

$server = new Server('127.0.0.1', $port);

$server->listen(function (Request $request) {
	return new Response('Hewro Worldo');
});
